name: Debug Runner

on:
  push:
    branches: [main, feature-tests-on-ci]
  pull_request:
    branches: [main, feature-tests-on-ci]

jobs:
  test-connection:
    runs-on: self-hosted
    steps:
      - name: Simple Echo
        run: echo "The runner is alive at $(date)"
